language: node_js
node_js:
- stable
branches:
  only:
  - master
install: cd ./app/web && npm install
cache:
  directories:
    - ./app/web/node_modules
script: cd ./app/web && npm test
after_success:
  - cd ./app/web
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)